spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delievery_system?serverTimezone=UTC
    username: root
    password:

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  application:
    name: product-service

server:
  port: 8082